// ============================================================
// GULTUVAK — O'simliklar ma'lumotlar bazasi (statik, offline ishlaydi)
// Bu massiv "plants.html" va "plant-detail.html" sahifalarida ishlatiladi.
// Keyinchalik bu ma'lumotlarni Supabase "plants" jadvaliga ko'chirish mumkin.
// ============================================================

const PLANTS_DATA = [
  { id: 1, name_uz: "Aloe Vera", latin_name: "Aloe vera", category: "Sukkulent", difficulty: "Oson", light: "Yorug', to'g'ridan-to'g'ri quyosh yaxshi", watering_days: 14, temp_min: 15, temp_max: 27, humidity: "Past", soil: "Kaktus/sukkulent tuprog'i, drenaj yaxshi bo'lsin", description: "Shifobaxsh xususiyatlari bilan mashhur, deyarli parvarishsiz o'suvchi sukkulent.", care_tips: "Tuproq to'liq quriganda sug'oring. Qishda sug'orishni kamaytiring.", warning_notes: "Ortiqcha sug'orish ildiz chirishiga olib keladi." },
  { id: 2, name_uz: "Ilon terisi (Sansevieriya)", latin_name: "Sansevieria trifasciata", category: "Sukkulent", difficulty: "Oson", light: "Soyada ham, yorug'da ham o'sadi", watering_days: 18, temp_min: 15, temp_max: 30, humidity: "Past", soil: "Yengil, drenajli tuproq", description: "Havoni tozalash xususiyati va chidamliligi bilan boshlovchilar uchun ideal.", care_tips: "Kam sug'oring, ortiqcha namlikdan qo'rqadi.", warning_notes: "Uy hayvonlari uchun zaharli, ehtiyot bo'ling." },
  { id: 3, name_uz: "Dollar daraxti (Zamiokulkas)", latin_name: "Zamioculcas zamiifolia", category: "Sukkulent", difficulty: "Oson", light: "Yorug', bevosita quyoshsiz", watering_days: 14, temp_min: 16, temp_max: 28, humidity: "Past", soil: "Drenajli, sukkulent tuprog'i", description: "Qurg'oqchilikka chidamli, yorqin yashil bargli, mashhur uy o'simligi.", care_tips: "Tuproq quruq bo'lgandagina sug'oring.", warning_notes: "Bargi zaharli, bolalardan uzoqroqqa qo'ying." },
  { id: 4, name_uz: "Benjamin fikusi", latin_name: "Ficus benjamina", category: "Bezakli-bargli", difficulty: "O'rta", light: "Yorug', lekin to'g'ridan-to'g'ri quyoshsiz", watering_days: 6, temp_min: 16, temp_max: 26, humidity: "O'rta", soil: "Universal gulzor tuprog'i", description: "Ingichka barglari va shoxlab o'sishi bilan mashhur, xona muhitini yashillashtiradi.", care_tips: "Joyini tez-tez o'zgartirmang — barg to'kilishiga olib kelishi mumkin.", warning_notes: "Shamol va sovuqdan saqlang." },
  { id: 5, name_uz: "Rezina fikus", latin_name: "Ficus elastica", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorug', yarim soya", watering_days: 7, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Yengil, drenajli tuproq", description: "Katta, yaltiroq barglari bilan xonaga zamonaviy ko'rinish beradi.", care_tips: "Barglarini nam mato bilan artib turing — chang yig'iladi.", warning_notes: "Shirasi teriga tegsa qichishtirishi mumkin." },
  { id: 6, name_uz: "Monstera", latin_name: "Monstera deliciosa", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 7, temp_min: 18, temp_max: 27, humidity: "Yuqori", soil: "Nam ushlovchi, drenajli tuproq", description: "Katta teshikli barglari bilan interyer dizaynida sevimli o'simlik.", care_tips: "Tayoqchaga o'rab yuqoriga o'stiring, barglarini purkab turing.", warning_notes: "" },
  { id: 7, name_uz: "Piley (Pul gullari)", latin_name: "Pilea peperomioides", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 6, temp_min: 15, temp_max: 24, humidity: "O'rta", soil: "Yengil, drenajli tuproq", description: "Yumaloq tanga-shakl barglari bilan ijtimoiy tarmoqlarda mashhur bo'lgan o'simlik.", care_tips: "Har hafta bir marta 90 daraja aylantiring — tekis o'sadi.", warning_notes: "" },
  { id: 8, name_uz: "Er baxti (Spatifillum)", latin_name: "Spathiphyllum", category: "Gulli", difficulty: "Oson", light: "Yarim soya", watering_days: 5, temp_min: 18, temp_max: 26, humidity: "Yuqori", soil: "Nam ushlovchi tuproq", description: "Oq gullari va oilaviy baxt ramzi sifatida uylarda ko'p yetishtiriladi.", care_tips: "Barglari osilib qolsa — sug'orish vaqti keldi degani.", warning_notes: "Bargi va guli zaharli, uy hayvonlaridan uzoqroqqa qo'ying." },
  { id: 9, name_uz: "Antorium", latin_name: "Anthurium andraeanum", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 6, temp_min: 18, temp_max: 27, humidity: "Yuqori", soil: "Orxideya aralashmasiga yaqin, havodor tuproq", description: "Yorqin qizil-pushti \"yurak\" shaklidagi gullari bilan ajralib turadi.", care_tips: "Haftasiga bir necha marta purkab turing, quruq havoni yoqtirmaydi.", warning_notes: "Zaharli, ehtiyot bo'ling." },
  { id: 10, name_uz: "Orxideya (Falenopsis)", latin_name: "Phalaenopsis", category: "Gulli", difficulty: "Qiyin", light: "Yorqin, sochilgan yorug'lik", watering_days: 7, temp_min: 18, temp_max: 28, humidity: "Yuqori", soil: "Orxideya po'stlog'i aralashmasi", description: "Nafis va uzoq gullaydigan, ammo alohida parvarish talab qiladigan gul.", care_tips: "Idishni suvga 15 daqiqa botirib, keyin quriting — bu 'g'ovaklash' usuli.", warning_notes: "Ildizlariga suv turib qolishiga yo'l qo'ymang." },
  { id: 11, name_uz: "Uzambar binafshasi", latin_name: "Saintpaulia", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 18, temp_max: 24, humidity: "O'rta", soil: "Yengil, g'ovak tuproq", description: "Mayin tuk bilan qoplangan barglari va rangdor kichik gullari bilan mashhur.", care_tips: "Barglarga suv tegmasin — dog' qoladi, faqat tuvakka sug'oring.", warning_notes: "" },
  { id: 12, name_uz: "Kaktus (aralash turlar)", latin_name: "Cactaceae", category: "Sukkulent", difficulty: "Oson", light: "To'g'ridan-to'g'ri quyosh", watering_days: 20, temp_min: 10, temp_max: 32, humidity: "Past", soil: "Kaktus tuprog'i, qumli", description: "Deyarli parvarishsiz, quyoshsevar va chidamli o'simlik oilasi.", care_tips: "Qishda oyiga 1 marta yoki umuman sug'ormang.", warning_notes: "Tikanlaridan ehtiyot bo'ling." },
  { id: 13, name_uz: "Chinni gul (Gibiskus)", latin_name: "Hibiscus rosa-sinensis", category: "Gulli", difficulty: "O'rta", light: "To'liq quyosh", watering_days: 4, temp_min: 16, temp_max: 28, humidity: "O'rta", soil: "Unumdor, drenajli tuproq", description: "Yirik va yorqin gullari bilan bog'-tomorqa uslubini uyga olib kiradi.", care_tips: "Gullash davrida haftasiga o'g'itlang.", warning_notes: "" },
  { id: 14, name_uz: "Pelargoniya (Geran)", latin_name: "Pelargonium", category: "Gulli", difficulty: "Oson", light: "To'liq quyosh", watering_days: 6, temp_min: 12, temp_max: 26, humidity: "Past", soil: "Yengil, drenajli tuproq", description: "O'ziga xos hidi va rang-barang gullari bilan tanish, uzoq gullaydigan o'simlik.", care_tips: "Quriган gullarni muntazam kesib turing — yangi gullashni rag'batlantiradi.", warning_notes: "" },
  { id: 15, name_uz: "Bonsay fikus", latin_name: "Ficus microcarpa", category: "Bonsay", difficulty: "Qiyin", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Bonsay aralashmasi", description: "Kichik hajmda daraxt shaklini saqlaydigan san'at o'simligi.", care_tips: "Muntazam shakl berish (obrezka) talab qiladi.", warning_notes: "" },
  { id: 16, name_uz: "Dracena marginata", latin_name: "Dracaena marginata", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 8, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Universal tuproq", description: "Ingichka, qizil chetli barglari bilan minimalist interyerga mos keladi.", care_tips: "Ftorli suvdan saqlaning — barg uchlari qorayadi.", warning_notes: "Mushuklar uchun zaharli." },
  { id: 17, name_uz: "Baxt daraxti (Draцena)", latin_name: "Dracaena fragrans", category: "Bezakli-bargli", difficulty: "Oson", light: "Yarim soya", watering_days: 7, temp_min: 18, temp_max: 26, humidity: "O'rta", soil: "Universal tuproq", description: "Baland, palmasimon ko'rinishga ega, ofis va uylarda keng tarqalgan.", care_tips: "Barglarini vaqti-vaqti bilan chang bosishdan tozalab turing.", warning_notes: "" },
  { id: 18, name_uz: "O'rgimchak gul (Xlorofitum)", latin_name: "Chlorophytum comosum", category: "Ampel", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 6, temp_min: 15, temp_max: 26, humidity: "O'rta", soil: "Universal tuproq", description: "Havoni tozalovchi va tez ko'payuvchi, osma tuvaklar uchun ideal.", care_tips: "Yon novdalarini kesib olib, yangi tuvakka ekish orqali ko'paytiring.", warning_notes: "" },
  { id: 19, name_uz: "Peperomiya", latin_name: "Peperomia obtusifolia", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 9, temp_min: 18, temp_max: 26, humidity: "O'rta", soil: "Yengil, drenajli tuproq", description: "Ixcham, go'shtdor barglari bilan kichik joylarga mos keluvchi o'simlik.", care_tips: "Ortiqcha sug'orishdan saqlaning, sukkulentga yaqin parvarish talab etadi.", warning_notes: "" },
  { id: 20, name_uz: "Kalateya", latin_name: "Calathea orbifolia", category: "Bezakli-bargli", difficulty: "Qiyin", light: "Yarim soya", watering_days: 5, temp_min: 18, temp_max: 26, humidity: "Yuqori", soil: "Nam ushlovchi tuproq", description: "Naqshli, rang-barang barglari kechqurun yig'ilishi bilan mashhur.", care_tips: "Faqat filtrlangan yoki tindirilgan suv bilan sug'oring.", warning_notes: "Quruq havoda barg uchlari quriydi." },
  { id: 21, name_uz: "Aglaonema", latin_name: "Aglaonema commutatum", category: "Bezakli-bargli", difficulty: "Oson", light: "Kam yorug'likka chidamli", watering_days: 7, temp_min: 18, temp_max: 27, humidity: "O'rta", soil: "Universal tuproq", description: "Kam yorug'li xonalarda ham chiroyli o'sadigan bargli o'simlik.", care_tips: "Sovuq shamoldan himoya qiling.", warning_notes: "" },
  { id: 22, name_uz: "Kroton", latin_name: "Codiaeum variegatum", category: "Bezakli-bargli", difficulty: "O'rta", light: "Yorqin, to'g'ridan-to'g'ri quyosh yaxshi", watering_days: 5, temp_min: 18, temp_max: 27, humidity: "Yuqori", soil: "Unumdor tuproq", description: "Rang-barang, sariq-qizil naqshli barglari bilan diqqatni tortadi.", care_tips: "Yetarli yorug'lik bo'lmasa ranglar so'lg'inlashadi.", warning_notes: "Shirasi zaharli." },
  { id: 23, name_uz: "Begoniya", latin_name: "Begonia", category: "Gulli", difficulty: "O'rta", light: "Yarim soya", watering_days: 5, temp_min: 16, temp_max: 25, humidity: "O'rta", soil: "Yengil, drenajli tuproq", description: "Turli xil bargi va gullari bilan boy assortimentga ega mashhur oila.", care_tips: "Barglariga suv tegishidan saqlaning — chirish xavfi bor.", warning_notes: "" },
  { id: 24, name_uz: "Fuksiya", latin_name: "Fuchsia", category: "Ampel", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 4, temp_min: 14, temp_max: 22, humidity: "O'rta", soil: "Unumdor, drenajli tuproq", description: "Osilib turuvchi, 'baletchi ko'ylagi' shaklidagi gullari bilan mashhur.", care_tips: "Issiqda tez quriydi, tuprog'ini doim biroz nam saqlang.", warning_notes: "" },
  { id: 25, name_uz: "Yasmin (Jasmin)", latin_name: "Jasminum polyanthum", category: "Gulli", difficulty: "O'rta", light: "Yorqin, to'g'ridan-to'g'ri quyosh yaxshi", watering_days: 5, temp_min: 15, temp_max: 24, humidity: "O'rta", soil: "Unumdor tuproq", description: "Kuchli xushbo'y hidli, oq mayda gullari bilan sevimli o'simlik.", care_tips: "Gullashdan keyin shoxlarini kesib qo'llab-quvvatlang.", warning_notes: "" },
  { id: 26, name_uz: "Uy atirguli", latin_name: "Rosa (mini)", category: "Gulli", difficulty: "Qiyin", light: "To'liq quyosh", watering_days: 3, temp_min: 15, temp_max: 24, humidity: "O'rta", soil: "Unumdor, drenajli tuproq", description: "Kichik tuvak uchun moslashtirilgan, klassik go'zallikdagi gul.", care_tips: "Muntazam o'g'itlash va yaxshi shamollatish zarur.", warning_notes: "Zararkunandalarga moyil, tez-tez tekshirib turing." },
  { id: 27, name_uz: "Tsiklamen", latin_name: "Cyclamen persicum", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sovuqroq joy", watering_days: 5, temp_min: 10, temp_max: 18, humidity: "O'rta", soil: "Yengil, drenajli tuproq", description: "Qishki gullashi va nafis shakldagi gullari bilan ajralib turadi.", care_tips: "Issiq xonadan saqlang — issiqlik gullashni to'xtatadi.", warning_notes: "Tuganak zaharli." },
  { id: 28, name_uz: "Kalanхoe", latin_name: "Kalanchoe blossfeldiana", category: "Sukkulent", difficulty: "Oson", light: "Yorqin", watering_days: 12, temp_min: 15, temp_max: 26, humidity: "Past", soil: "Sukkulent tuprog'i", description: "Yorqin to'p-to'p gullari bilan uzoq muddat quvontiradigan sukkulent.", care_tips: "Gullashdan so'ng so'lgan poyalarni kesib tashlang.", warning_notes: "Uy hayvonlari uchun zaharli." },
  { id: 29, name_uz: "Aspidistra (Temir gul)", latin_name: "Aspidistra elatior", category: "Bezakli-bargli", difficulty: "Oson", light: "Soyaga chidamli", watering_days: 8, temp_min: 12, temp_max: 25, humidity: "Past", soil: "Universal tuproq", description: "Nomidek 'temir' chidamlilikka ega, deyarli o'lmaydigan o'simlik.", care_tips: "E'tiborsizlikka eng chidamli o'simliklardan biri.", warning_notes: "" },
  { id: 30, name_uz: "Xamedoreya palmasi", latin_name: "Chamaedorea elegans", category: "Palma", difficulty: "Oson", light: "Yarim soya", watering_days: 6, temp_min: 16, temp_max: 26, humidity: "O'rta", soil: "Universal tuproq", description: "Kichik xonalar uchun mos, ixcham palma turi.", care_tips: "Barg uchlari qorayib qolsa — havo namligini oshiring.", warning_notes: "" },
  { id: 31, name_uz: "Yukka", latin_name: "Yucca elephantipes", category: "Bezakli-bargli", difficulty: "Oson", light: "To'liq quyosh", watering_days: 12, temp_min: 15, temp_max: 28, humidity: "Past", soil: "Drenajli tuproq", description: "Cho'l mintaqasidan kelib chiqqan, qurg'oqchilikka juda chidamli o'simlik.", care_tips: "Kam sug'oring, ortiqcha suv ildizni chiritadi.", warning_notes: "" },
  { id: 32, name_uz: "Asparagus (Sparja)", latin_name: "Asparagus setaceus", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 6, temp_min: 15, temp_max: 24, humidity: "O'rta", soil: "Yengil tuproq", description: "Yengil, ninabargsimon shoxlari bilan nafis ko'rinishga ega.", care_tips: "Havo namligini yoqtiradi, purkab turing.", warning_notes: "" },
  { id: 33, name_uz: "Paporotnik (Nefrolepis)", latin_name: "Nephrolepis exaltata", category: "Papоротnik", difficulty: "O'rta", light: "Yarim soya", watering_days: 4, temp_min: 16, temp_max: 24, humidity: "Yuqori", soil: "Nam ushlovchi tuproq", description: "Yashil, uzun barglari bilan hammomga ham mos keladigan namsevar o'simlik.", care_tips: "Tuprog'i hech qachon to'liq qurib qolmasin.", warning_notes: "" },
  { id: 34, name_uz: "Traditsanciya (Zebra o'simligi)", latin_name: "Tradescantia zebrina", category: "Ampel", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 15, temp_max: 25, humidity: "O'rta", soil: "Universal tuproq", description: "Kumushrang-binafsha yo'l-yo'l barglari bilan osma tuvaklarda chiroyli ko'rinadi.", care_tips: "Tez o'sadi, vaqti-vaqti bilan qirqib turish shaklini saqlaydi.", warning_notes: "" },
  { id: 35, name_uz: "Mum gul (Xoya)", latin_name: "Hoya carnosa", category: "Ampel", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 12, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Havodor, drenajli tuproq", description: "Mumsimon, yulduzcha gullari va uzun lianasi bilan sevimli o'simlik.", care_tips: "So'lgan gul poyalarini kesmang — ular qayta gullaydi.", warning_notes: "" },
  { id: 36, name_uz: "Sissus", latin_name: "Cissus rhombifolia", category: "Ampel", difficulty: "Oson", light: "Yarim soya", watering_days: 6, temp_min: 15, temp_max: 25, humidity: "O'rta", soil: "Universal tuproq", description: "Tez o'suvchi, uzuk barglari bilan devor yoki panjaraga o'raladigan liana.", care_tips: "Tayanch bering — o'zi ilashib o'sadi.", warning_notes: "" },
  { id: 37, name_uz: "Pul daraxti (Epipremnum)", latin_name: "Epipremnum aureum", category: "Ampel", difficulty: "Oson", light: "Kam yorug'likka chidamli", watering_days: 7, temp_min: 15, temp_max: 27, humidity: "O'rta", soil: "Universal tuproq", description: "Eng chidamli va tez o'suvchi liana turlaridan biri, boshlovchilar uchun ideal.", care_tips: "Suvda ham, tuproqda ham ildiz otadi — ko'paytirish oson.", warning_notes: "Uy hayvonlari uchun zaharli." },
  { id: 38, name_uz: "Filodendron", latin_name: "Philodendron hederaceum", category: "Ampel", difficulty: "Oson", light: "Yarim soya", watering_days: 7, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Universal tuproq", description: "Yurak shaklidagi yaltiroq barglari bilan tez o'sadigan liana.", care_tips: "Tayoqchaga o'rab yuqoriga yo'naltirish mumkin.", warning_notes: "" },
  { id: 39, name_uz: "Alokaziya", latin_name: "Alocasia amazonica", category: "Bezakli-bargli", difficulty: "Qiyin", light: "Yorqin, sochilgan yorug'lik", watering_days: 6, temp_min: 18, temp_max: 27, humidity: "Yuqori", soil: "Havodor, nam ushlovchi tuproq", description: "O'q shaklidagi barglaridagi kumushrang tomirlari bilan tropik go'zallik.", care_tips: "Havo namligi past bo'lsa purkagich ishlating.", warning_notes: "Zaharli." },
  { id: 40, name_uz: "Guzmaniya (Bromeliya)", latin_name: "Guzmania", category: "Bromeliya", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 18, temp_max: 26, humidity: "Yuqori", soil: "Havodor, engil tuproq", description: "Markazidagi yorqin rangli 'stakan'ga suv to'ldirib o'stiriladigan tropik o'simlik.", care_tips: "Markaziy 'stakanchasiga' toza suv quyib turing.", warning_notes: "" },
  { id: 41, name_uz: "Azaliya", latin_name: "Rhododendron simsii", category: "Gulli", difficulty: "Qiyin", light: "Yorqin, sovuqroq joy", watering_days: 3, temp_min: 12, temp_max: 18, humidity: "Yuqori", soil: "Kislotali, torfli tuproq", description: "Zich, rang-barang gullari bilan qishki bezak sifatida mashhur.", care_tips: "Faqat yumshoq (tindirilgan) suv bilan sug'oring.", warning_notes: "Barglari zaharli." },
  { id: 42, name_uz: "Primula", latin_name: "Primula vulgaris", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sovuqroq joy", watering_days: 3, temp_min: 10, temp_max: 18, humidity: "O'rta", soil: "Unumdor tuproq", description: "Erta bahorda gullaydigan, rang-barang va ixcham gul.", care_tips: "Issiqdan saqlang, salqin joy gullashni uzaytiradi.", warning_notes: "" },
  { id: 43, name_uz: "Siperus (Suv o'simligi)", latin_name: "Cyperus alternifolius", category: "Suvsevar", difficulty: "Oson", light: "Yarim soya", watering_days: 2, temp_min: 16, temp_max: 26, humidity: "Yuqori", soil: "Doim nam tuproq", description: "Fаvvora shaklidagi barglari bilan namlikni yaxshi ko'radigan o'simlik.", care_tips: "Tuvak ostidagi likobchada doim biroz suv turishi mumkin.", warning_notes: "" },
  { id: 44, name_uz: "Adenium (Cho'l atirguli)", latin_name: "Adenium obesum", category: "Sukkulent", difficulty: "O'rta", light: "To'liq quyosh", watering_days: 12, temp_min: 18, temp_max: 32, humidity: "Past", soil: "Sukkulent tuprog'i", description: "Shishgan poyasi va yorqin gullari bilan ekzotik ko'rinishga ega.", care_tips: "Qishda deyarli sug'ormang, o'simlik dam olish holatiga o'tadi.", warning_notes: "Shirasi zaharli." },
  { id: 45, name_uz: "Echeveriya", latin_name: "Echeveria elegans", category: "Sukkulent", difficulty: "Oson", light: "To'liq quyosh", watering_days: 14, temp_min: 15, temp_max: 27, humidity: "Past", soil: "Sukkulent tuprog'i", description: "Gul-atirgulga o'xshash rozetka shaklidagi barglari bilan mashhur sukkulent.", care_tips: "Sug'organda barglarga suv tekkizmang.", warning_notes: "" },
  { id: 46, name_uz: "Xavorтiya", latin_name: "Haworthia fasciata", category: "Sukkulent", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 15, temp_min: 15, temp_max: 26, humidity: "Past", soil: "Sukkulent tuprog'i", description: "Kichik hajmi va oq chiziqli barglari bilan tokchalar uchun ideal.", care_tips: "Kichik idishlarda ham yaxshi o'sadi.", warning_notes: "" },
  { id: 47, name_uz: "Pul daraxtchasi (Krassula)", latin_name: "Crassula ovata", category: "Sukkulent", difficulty: "Oson", light: "Yorqin", watering_days: 14, temp_min: 15, temp_max: 27, humidity: "Past", soil: "Sukkulent tuprog'i", description: "Yumaloq, go'shtdor barglari bois 'pul daraxti' deb ataladi.", care_tips: "Bir tekis quyosh tushishi uchun tuvakni burab turing.", warning_notes: "" },
  { id: 48, name_uz: "Sheffлera", latin_name: "Schefflera arboricola", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 7, temp_min: 16, temp_max: 26, humidity: "O'rta", soil: "Universal tuproq", description: "Panjasimon barglari bilan mini-daraxt ko'rinishini beradi.", care_tips: "Bir tomonga engashib o'ssa, tuvakni burab turing.", warning_notes: "" },
  { id: 49, name_uz: "Krevetka gul (Beloperone)", latin_name: "Justicia brandegeeana", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 16, temp_max: 26, humidity: "O'rta", soil: "Unumdor tuproq", description: "Krevetkaga o'xshash noodatiy pushti-jigarrang gul boshoqlari bilan ajralib turadi.", care_tips: "Gullashni rag'batlantirish uchun muntazam kesib turing.", warning_notes: "" },
  { id: 50, name_uz: "Streptokarpus", latin_name: "Streptocarpus", category: "Gulli", difficulty: "O'rta", light: "Yorqin, sochilgan yorug'lik", watering_days: 5, temp_min: 16, temp_max: 24, humidity: "O'rta", soil: "Yengil, g'ovak tuproq", description: "Binafshaga o'xshash, ammo uzunroq gullari bilan uzoq muddat gullaydi.", care_tips: "Pastdan (likobcha orqali) sug'organi ma'qul.", warning_notes: "" },
  { id: 51, name_uz: "Koleus", latin_name: "Coleus scutellarioides", category: "Bezakli-bargli", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 4, temp_min: 16, temp_max: 27, humidity: "O'rta", soil: "Unumdor tuproq", description: "Rang-barang, naqshli barglari bilan gulsiz ham juda bezakli o'simlik.", care_tips: "Gulga kirsa, ranglar yo'qolmasligi uchun gul boshoqlarini kesib tashlang.", warning_notes: "" },
  { id: 52, name_uz: "Yalpiz", latin_name: "Mentha", category: "Ziravor", difficulty: "Oson", light: "Yorqin, sochilgan yorug'lik", watering_days: 3, temp_min: 14, temp_max: 26, humidity: "O'rta", soil: "Unumdor, nam tuproq", description: "Xushbo'y hidli, choy va taomlar uchun uyda yetishtiriladigan ziravor o'simlik.", care_tips: "Tuprog'i doim biroz nam bo'lishini yoqtiradi.", warning_notes: "" },
  { id: 53, name_uz: "Rayhon", latin_name: "Ocimum basilicum", category: "Ziravor", difficulty: "Oson", light: "To'liq quyosh", watering_days: 3, temp_min: 18, temp_max: 28, humidity: "O'rta", soil: "Unumdor tuproq", description: "Milliy taomlarda keng qo'llaniladigan, uy sharoitida oson yetishtiriladigan ziravor.", care_tips: "Uchki barglarini muntazam terib turish shoxlashni rag'batlantiradi.", warning_notes: "" }
];

// Kategoriyalar ro'yxati (filter uchun)
const PLANT_CATEGORIES = [...new Set(PLANTS_DATA.map(p => p.category))].sort();
